version: "3.9"

services:
  users-api:
    build: ./users-api
    container_name: users-api
    environment:
      # API Config
      - PORT=4001
      - SERVICE_NAME=users-api
      
      # CLOUD SQL DATABASE CONFIGURATION
      - DB_HOST=34.45.61.250              # <--- IP Pública de tu instancia dbmulti-apis
      - DB_USER=postgres
      - DB_PASSWORD=Aa1005312807$        # <--- ¡REEMPLAZAR con tu contraseña real!
      - DB_NAME=basededatosgoogle
      
    ports:
      - "4001:4001"
    restart: unless-stopped

  products-api:
    build: ./products-api
    container_name: products-api
    environment:
      # API Config
      - PORT=4002
      - SERVICE_NAME=products-api
      - USERS_API_URL=http://users-api:4001
      
      # CLOUD SQL DATABASE CONFIGURATION
      - DB_HOST=34.45.61.250              # <--- Misma IP Pública
      - DB_USER=postgres
      - DB_PASSWORD=Aa1005312807$        # <--- ¡REEMPLAZAR con tu contraseña real!
      - DB_NAME=basededatosgoogle
      
    ports:
      - "4002:4002"
    depends_on:
      - users-api
    restart: unless-stopped